dofile("! L_HookLibrary.lua")
dofile("OptionSaving.lua")
dofile("randomizer.lua")
dofile("( - Setup.lua")
dofile("- - WpnSetup.lua")
dofile("Sprayer.lua")
dofile("Addon Support.lua")
dofile("death.lua")
dofile("Freeman Thinker.lua")
dofile("Shooting Thinker.lua")
dofile("object setup.lua")
dofile("HUD.lua")
dofile("Steam2011Menu.lua")
dofile("L_Footsteps-v2.3.lua")
dofile("L_QuakePhysicsV1.lua")
dofile("L_QuakeViewroll-v1.0.1.lua")
dofile("GrindsMyGears.lua")
-- TODO: Credit https://mb.srb2.org/addons/stickers-for-srb2.8129/